import { ArrowLeft, ArrowDown, ArrowUp } from "lucide-react";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { EditorActions, SelectField, TextField } from "@/components/shared/workspace-ui";
import type { ActionDefinition, AgentDefinition } from "@shared/orchestration/environment";
import type { ResourceDocument } from "../types";
import { validateActionInstruction, REQUIRED_ACTION_INSTRUCTION_SECTIONS } from "@shared/orchestration/instructionContract";
import { ConfigureHeader, IssueList } from "./ConfigureHeader";
import { ConfigureToolbar } from "./ConfigureToolbar";

export function ActionWorkspace({ stateId, action, profiles, instructions, skills, locked, canvasMode, canMoveEarlier, canMoveLater, navigate, onCanvasModeChange, onMove, onDelete, onSave }: { stateId?: string; action?: ActionDefinition; profiles: AgentDefinition[]; instructions: ResourceDocument[]; skills: ResourceDocument[]; locked: boolean; canvasMode?: "flow"; canMoveEarlier?: boolean; canMoveLater?: boolean; navigate(path: string): void; onCanvasModeChange(mode: "space" | "flow"): void; onMove?(delta: -1 | 1): Promise<void>; onDelete?(): Promise<void>; onSave(action: ActionDefinition): Promise<void> }) {
  const [draft, setDraft] = useState(action);
  if (!stateId || !action || !draft) return <><ConfigureHeader title="Action not found" description="The State or Action ID in this deep link is invalid." status="Invalid ID" /><div className="p-6"><Button onClick={() => navigate("/automation/loops")}>Return to Environment</Button></div></>;
  const instructionIssues = [draft.validation, draft.work].flatMap((composition) => { const document = instructions.find((item) => item.id === composition.instructionResource); return document ? validateActionInstruction(document.content) : [{ path: composition.instructionResource, message: "Instruction resource not found" }]; });
  const status = locked ? "Locked by active Run" : instructionIssues.length ? "Not ready" : "Ready"; const formId = `action-${action.id}`; const dirty = JSON.stringify(draft) !== JSON.stringify(action);
  return <><ConfigureHeader title={action.name} description="Validation is the main controller; Work is a subordinate execution role." /><ConfigureToolbar status={status} label={action.id}><Button variant="outline" onClick={() => navigate(`/automation/loops/states/${encodeURIComponent(stateId)}`)}><ArrowLeft />State</Button><Button variant="outline" disabled={locked || !canMoveEarlier} onClick={() => void onMove?.(-1)}><ArrowUp />Earlier</Button><Button variant="outline" disabled={locked || !canMoveLater} onClick={() => void onMove?.(1)}><ArrowDown />Later</Button><Button variant="outline" onClick={() => onCanvasModeChange(canvasMode === "flow" ? "space" : "flow")}>{canvasMode === "flow" ? "Show space canvas" : "Open Action flow"}</Button><EditorActions saveLabel="Save Action" formId={formId} dirty={dirty} valid={!locked && instructionIssues.length === 0} canDelete={Boolean(onDelete)} deleteLabel="Delete Action" deleteType="Action" resourceName={action.name} onDelete={onDelete} /></ConfigureToolbar>
    <div className="min-w-0 space-y-4 p-4 md:p-6"><form id={formId} className="min-w-0 space-y-4 rounded-md border bg-card p-4" onSubmit={(event) => { event.preventDefault(); void onSave(draft); }}><div><h2 className="font-semibold">Action metadata</h2><code className="text-xs text-tertiary">{draft.id}</code></div><TextField label="Name" layout="row" density="compact" value={draft.name} onChange={(name) => setDraft({ ...draft, name })} /><TextField label="Description" layout="row" density="compact" value={draft.description} onChange={(description) => setDraft({ ...draft, description })} /><TextField label="Priority" layout="row" density="compact" type="number" value={draft.priority} onChange={(value) => setDraft({ ...draft, priority: Number(value) })} /><TextField label="maxRetries" layout="row" density="compact" type="number" description={`Total maximum Work attempts: ${1 + draft.maxRetries}`} value={draft.maxRetries} onChange={(value) => setDraft({ ...draft, maxRetries: Number(value) })} /><TextField label="Use Case refs" layout="row" density="compact" value={draft.useCaseIds.join(", ")} onChange={(value) => setDraft({ ...draft, useCaseIds: value.split(",").map((item) => item.trim()).filter(Boolean) })} />
      <CompositionEditor role="Validation" composition={draft.validation} profiles={profiles} instructions={instructions} skills={skills} onChange={(validation) => setDraft({ ...draft, validation: { ...validation } })} /><CompositionEditor role="Work" composition={draft.work} profiles={profiles} instructions={instructions} skills={skills} onChange={(work) => setDraft({ ...draft, work: { ...work } })} /></form><section className="rounded-md border bg-card p-4"><h2 className="font-semibold">Run readiness</h2><p className="mb-2 text-xs text-muted-foreground">Required instruction sections: {REQUIRED_ACTION_INSTRUCTION_SECTIONS.join(" · ")}</p><IssueList issues={instructionIssues} /></section></div></>;
}

function CompositionEditor({ role, composition, profiles, instructions, skills, onChange }: { role: "Validation" | "Work"; composition: ActionDefinition["validation"]; profiles: AgentDefinition[]; instructions: ResourceDocument[]; skills: ResourceDocument[]; onChange(value: ActionDefinition["validation"]): void }) {
  return <fieldset className="space-y-3 rounded-sm border p-3"><legend className="font-semibold">{role} Agent · {role === "Validation" ? "main/controller" : "subordinate"}</legend><p className="text-xs text-muted-foreground">Permission: {role === "Validation" ? "read-only" : "workspace-write"}</p><SelectField label="Agent" layout="row" density="compact" value={composition.agentId} options={profiles.map((agent) => ({ value: agent.id, label: agent.name }))} onChange={(agentId) => onChange({ ...composition, agentId })} /><SelectField label="Instruction" layout="row" density="compact" value={composition.instructionResource} options={instructions.map((item) => ({ value: item.id, label: item.id }))} onChange={(instructionResource) => onChange({ ...composition, instructionResource })} /><TextField label="Skills" layout="row" density="compact" description={`Available: ${skills.map(({ id }) => id).join(" · ") || "none"}`} value={composition.skillResources.join(", ")} onChange={(value) => onChange({ ...composition, skillResources: value.split(",").map((item) => item.trim()).filter(Boolean) })} /></fieldset>;
}
