import { ArrowLeft, ArrowDown, ArrowUp } from "lucide-react";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Switch } from "@/components/ui/switch";
import { MultiSelect } from "@/components/ui/multi-select";
import { EditorActions, SelectField, TextAreaField, TextField } from "@/components/shared/workspace-ui";
import type { ActionDefinition } from "@shared/orchestration/environment";
import type { ResourceDocument } from "../types";
import { validateActionInstruction, REQUIRED_ACTION_INSTRUCTION_SECTIONS } from "@shared/orchestration/instructionContract";
import { ConfigureHeader, IssueList } from "./ConfigureHeader";
import { ConfigureToolbar } from "./ConfigureToolbar";
import { useActionRoleExecutionBinding } from "./useActionRoleExecutionBinding";
import type { ActionRoleExecutionState } from "./useActionRoleExecutionBinding";

export function ActionWorkspace({ stateId, action, instructions, skills, locked, canvasMode, canMoveEarlier, canMoveLater, navigate, onCanvasModeChange, onMove, onDelete, onSave }: { stateId?: string; action?: ActionDefinition; instructions: ResourceDocument[]; skills: ResourceDocument[]; locked: boolean; canvasMode?: "flow"; canMoveEarlier?: boolean; canMoveLater?: boolean; navigate(path: string): void; onCanvasModeChange(mode: "space" | "flow"): void; onMove?(delta: -1 | 1): Promise<void>; onDelete?(): Promise<void>; onSave(action: ActionDefinition): Promise<void> }) {
  const [draft, setDraft] = useState(action);
  const validationExecution = useActionRoleExecutionBinding(stateId ?? "", action?.id ?? "", "validation");
  const workExecution = useActionRoleExecutionBinding(stateId ?? "", action?.id ?? "", "work");
  if (!stateId || !action || !draft) return <><ConfigureHeader title="Action not found" description="The State or Action ID in this deep link is invalid." status="Invalid ID" /><div className="p-6"><Button onClick={() => navigate("/automation/loops")}>Return to Environment</Button></div></>;
  const instructionIssues = [draft.validation, draft.work].flatMap((composition) => { const document = instructions.find((item) => item.id === composition.instructionResource); return document ? validateActionInstruction(document.content) : [{ path: composition.instructionResource, message: "Instruction resource not found" }]; });
  const executionIssues = [...validationExecution.readinessIssues, ...workExecution.readinessIssues].map((message) => ({ path: "execution", message }));
  const readinessIssues = [...instructionIssues, ...executionIssues];
  const status = locked ? "Locked by active Run" : readinessIssues.length ? "Not ready" : "Ready"; const formId = `action-${action.id}`; const dirty = JSON.stringify(draft) !== JSON.stringify(action);
  return <><ConfigureHeader title={action.name} description="Validation is the main controller; Work is a subordinate execution role." /><ConfigureToolbar status={status} label={action.id}><Button variant="outline" onClick={() => navigate(`/automation/loops/states/${encodeURIComponent(stateId)}`)}><ArrowLeft />State</Button><Button variant="outline" disabled={locked || !canMoveEarlier} onClick={() => void onMove?.(-1)}><ArrowUp />Earlier</Button><Button variant="outline" disabled={locked || !canMoveLater} onClick={() => void onMove?.(1)}><ArrowDown />Later</Button><Button variant="outline" onClick={() => onCanvasModeChange(canvasMode === "flow" ? "space" : "flow")}>{canvasMode === "flow" ? "Show space canvas" : "Open Action flow"}</Button><EditorActions saveLabel="Save Action" formId={formId} dirty={dirty} valid={!locked && instructionIssues.length === 0} canDelete={Boolean(onDelete)} deleteLabel="Delete Action" deleteType="Action" resourceName={action.name} onDelete={onDelete} /></ConfigureToolbar>
    <div className="min-w-0 space-y-3 p-3 md:p-4"><form id={formId} className="min-w-0 space-y-3 border bg-card p-3 md:p-4" onSubmit={(event) => { event.preventDefault(); void onSave(draft); }}><TextField label="Name" layout="row" density="compact" value={draft.name} onChange={(name) => setDraft({ ...draft, name })} /><TextField label="Description" layout="row" density="compact" value={draft.description} onChange={(description) => setDraft({ ...draft, description })} /><TextField label="Priority" layout="row" density="compact" type="number" value={draft.priority} onChange={(value) => setDraft({ ...draft, priority: Number(value) })} /><TextField label="maxRetries" layout="row" density="compact" type="number" description={`Total maximum Work attempts: ${1 + draft.maxRetries}`} value={draft.maxRetries} onChange={(value) => setDraft({ ...draft, maxRetries: Number(value) })} />
      <CompositionEditor execution={validationExecution} role="Validation" composition={draft.validation} instructions={instructions} skills={skills} onChange={(validation) => setDraft({ ...draft, validation: { ...validation } })} /><CompositionEditor execution={workExecution} role="Work" composition={draft.work} instructions={instructions} skills={skills} onChange={(work) => setDraft({ ...draft, work: { ...work } })} /></form><section className="rounded-md border bg-card p-4"><h2 className="font-semibold">Run readiness</h2><p className="mb-2 text-xs text-muted-foreground">Required instruction sections: {REQUIRED_ACTION_INSTRUCTION_SECTIONS.join(" · ")}</p><IssueList issues={readinessIssues} /></section></div></>;
}

function CompositionEditor({ execution, role, composition, instructions, skills, onChange }: { execution: ActionRoleExecutionState; role: "Validation" | "Work"; composition: ActionDefinition["validation"]; instructions: ResourceDocument[]; skills: ResourceDocument[]; onChange(value: ActionDefinition["validation"]): void }) {
  const labelClass = "grid gap-1 text-xs md:grid-cols-[9rem_minmax(0,1fr)] md:items-center";
  return <fieldset className="space-y-3 rounded-sm border p-3"><legend className="font-semibold">{role} Agent · {role === "Validation" ? "main/controller" : "subordinate"}</legend><p className="text-xs text-muted-foreground">Permission: {role === "Validation" ? "read-only" : "workspace-write"} · execution changes apply to future Runs.</p>
    {execution.error ? <p role="alert" className="text-xs text-destructive">{execution.error}</p> : null}
    <SelectField label="Provider" layout="row" density="compact" value={execution.provider} placeholder="Select…" options={execution.providers.map((item) => ({ value: item.provider, label: `${item.provider} · ${item.health}` }))} onChange={execution.selectProvider} />
    <SelectField label="Model" layout="row" density="compact" value={execution.model} placeholder="Select…" options={execution.models.map((item) => ({ value: item.id, label: item.label }))} onChange={(model) => { execution.setModel(model); const selected = execution.models.find(({ id }) => id === model); execution.setReasoningEffort(selected?.defaultReasoning ?? selected?.reasoningOptions[0] ?? ""); }} />
    <SelectField label="Reasoning" layout="row" density="compact" value={execution.reasoningEffort} placeholder="Select…" options={execution.reasoningOptions.map((value) => ({ value, label: value }))} onChange={execution.setReasoningEffort} />
    <label className={labelClass}><span className="text-muted-foreground">Network</span><Switch aria-label={`${role} Network`} checked={execution.network} disabled={!execution.providerStatus?.capabilities.policy.networkControl} onCheckedChange={execution.setNetwork} /></label>
    <TextAreaField label="Read-only roots" layout="row" density="compact" value={execution.readOnlyRoots} disabled={!execution.providerStatus?.capabilities.policy.readOnlyRoots} placeholder="One absolute path per line" onChange={execution.setReadOnlyRoots} />
    <SelectField label="Instruction" layout="row" density="compact" value={composition.instructionResource} options={instructions.map((item) => ({ value: item.id, label: item.id }))} onChange={(instructionResource) => onChange({ ...composition, instructionResource })} />
    <label className={labelClass}><span className="text-muted-foreground">Skills</span><MultiSelect ariaLabel={`${role} Skills`} values={composition.skillResources} options={skills.map(({ id }) => ({ value: id, label: id }))} onValuesChange={(skillResources) => onChange({ ...composition, skillResources: [...skillResources].sort() })} /></label>
    <div className="flex items-center justify-between gap-3"><p className="text-xs text-muted-foreground">{execution.binding ? "Local execution binding saved" : "Execution binding required"}</p><Button type="button" size="sm" disabled={execution.pending || !execution.canSave} onClick={() => void execution.save()}>{execution.pending ? "Saving execution…" : "Save execution"}</Button></div>
  </fieldset>;
}
