import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Label } from "@/components/ui/label";
import { Switch } from "@/components/ui/switch";
import { SelectField, TextField } from "@/components/shared/workspace-ui";
import type { CriticConfiguration, CriticScheduleDefinition } from "@shared/orchestration/environment";
import { normalizeSchedule } from "../authoringModels";
import { ConfigureHeader } from "./ConfigureHeader";
import { ConfigureToolbar } from "./ConfigureToolbar";

export function CriticWorkspace({ critic, statuses, locked, onSave, onManual }: { critic: CriticConfiguration; statuses: Array<Record<string, unknown>>; locked: boolean; onSave(critic: CriticConfiguration): Promise<void>; onManual(): Promise<void> }) {
  const [draft, setDraft] = useState(critic); const [acknowledged, setAcknowledged] = useState(false);
  const updateSchedule = (index: number, next: CriticScheduleDefinition) => setDraft({ ...draft, schedules: draft.schedules.map((item, current) => current === index ? normalizeSchedule(next) : item) });
  const formId = "critic-configuration"; const valid = !locked && (!draft.enabled || acknowledged);
  return <><ConfigureHeader title="Critic configuration" description="Disabled by default. Due schedules and manual proposals run read-only; Save never runs or approves a proposal." /><ConfigureToolbar status={draft.enabled ? "Automatic schedules enabled" : "Disabled (default)"}><Button type="button" variant="outline" onClick={() => void onManual()}>Create critic proposal now</Button><Button type="submit" form={formId} disabled={!valid}>Save configuration</Button></ConfigureToolbar>
    <form id={formId} className="space-y-4 p-4 md:p-6" onSubmit={(event) => { event.preventDefault(); void onSave(draft); }}><section className="rounded-md border bg-card p-4"><div className="flex items-center justify-between gap-4"><div><Label htmlFor="critic-enabled">Enable automatic Critic schedules</Label><p className="text-sm text-muted-foreground">May incur provider cost and executes automatically when locally due.</p></div><Switch id="critic-enabled" checked={draft.enabled} onCheckedChange={(checked) => setDraft({ ...draft, enabled: checked })} /></div>{draft.enabled ? <label className="mt-3 flex min-h-10 items-center gap-2 text-sm"><input type="checkbox" checked={acknowledged} onChange={(event) => setAcknowledged(event.target.checked)} />I acknowledge automatic local execution and provider cost.</label> : null}</section>
      <section className="space-y-3"><h2 className="font-semibold">Daily and weekly schedules</h2>{draft.schedules.map((schedule, index) => <fieldset key={schedule.id} className="space-y-3 rounded-md border bg-card p-4"><legend className="px-1 font-mono text-xs text-tertiary">{schedule.id}</legend><SelectField label="Cadence" layout="row" density="compact" value={schedule.kind} options={[{ value: "daily", label: "Daily" }, { value: "weekly", label: "Weekly" }]} onChange={(value) => updateSchedule(index, value === "daily" ? { id: schedule.id, kind: "daily", timeZone: schedule.timeZone, localTimes: schedule.localTimes } : { id: schedule.id, kind: "weekly", timeZone: schedule.timeZone, localTimes: schedule.localTimes, weekdays: [1] })} /><TextField label="IANA timezone" layout="row" density="compact" value={schedule.timeZone} onChange={(timeZone) => updateSchedule(index, { ...schedule, timeZone })} /><TextField label="Local times" layout="row" density="compact" value={schedule.localTimes.join(", ")} onChange={(value) => updateSchedule(index, { ...schedule, localTimes: value.split(",") })} />{schedule.kind === "weekly" ? <TextField label="ISO weekdays" layout="row" density="compact" value={schedule.weekdays.join(", ")} onChange={(value) => updateSchedule(index, { ...schedule, weekdays: value.split(",").map(Number) })} /> : null}<p className="text-xs text-muted-foreground">Next due / last run: {JSON.stringify(statuses.find((status) => status.critic_schedule_id === schedule.id) ?? "not scheduled")}</p></fieldset>)}</section>
      <section className="rounded-md border bg-card p-4"><h2 className="font-semibold">Agent composition</h2><p className="text-sm text-muted-foreground">Profile <code>{draft.agent.agentId}</code> · Codex TOML developer instructions · read-only · {draft.agent.skillResources.length} Skills.</p></section>
      <p className="text-xs text-muted-foreground">Manual creation is separate from approval. It requires an existing Run Evidence and does not create Feedback.</p></form></>;
}
