import { useMemo, useState } from "react";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { OperationalStatus } from "@/components/shared/workspace-ui";
import type { UseCase, UseCaseExample } from "@shared/orchestration/direction";
import { useCaseApprovalHash } from "@shared/orchestration/direction";
import type { ResourceDocument } from "../types";
import { ConfigureHeader } from "./ConfigureHeader";

const emptyUseCase = (): UseCase => ({ id: "", name: "", status: "draft", examples: [{ given: "", when: "", then: "" }], successGoals: [], failureGoals: [], expectedOutcomes: [], goalIds: [], adrIds: [], constraintIds: [] });

export function UseCasesWorkspace({ useCases, documents, locked, environmentUsage, onSave, onApprove, onDraft }: {
  useCases: UseCase[]; documents: ResourceDocument[]; locked: boolean; environmentUsage: string[];
  onSave(value: UseCase, markdown: string, creating: boolean): Promise<void>; onApprove(value: UseCase): Promise<void>; onDraft(value: UseCase): Promise<void>;
}) {
  const [filter, setFilter] = useState<"all" | UseCase["status"]>("all"); const [selectedId, setSelectedId] = useState<string>();
  const [creating, setCreating] = useState(false);
  const filtered = useMemo(() => useCases.filter((item) => filter === "all" || item.status === filter), [filter, useCases]);
  const selected = useCases.find((item) => item.id === selectedId);
  return <><ConfigureHeader title="Use Cases" description="Given–When–Then intent becomes executable only through an explicit human approval command." status={locked ? "Locked by active Run" : `${useCases.filter((item) => item.status === "approved").length} approved`} actions={<Button size="sm" disabled={locked} onClick={() => { setCreating(true); setSelectedId(undefined); }}>Create draft</Button>} />
    <div className="grid min-w-0 gap-4 p-4 md:grid-cols-[minmax(16rem,0.72fr)_minmax(0,1.28fr)] md:p-6"><section><Label htmlFor="use-case-filter">Filter by status</Label><select id="use-case-filter" className="mb-3 h-10 w-full rounded-sm border bg-background px-2" value={filter} onChange={(event) => setFilter(event.target.value as typeof filter)}><option value="all">All</option><option value="draft">Draft</option><option value="approved">Approved</option></select><ul className="space-y-2">{filtered.map((item) => <li key={item.id}><button className="w-full rounded-md border bg-card p-3 text-left hover:bg-accent" onClick={() => { setCreating(false); setSelectedId(item.id); }}><span className="flex items-center justify-between"><code className="text-tertiary">{item.id}</code><OperationalStatus compact label={item.status} tone={item.status === "approved" ? "healthy" : "attention"} /></span><strong className="mt-1 block">{item.name}</strong><span className="text-xs text-muted-foreground">{item.examples.length} GWT example{item.examples.length === 1 ? "" : "s"}</span></button></li>)}</ul></section>
      {selected || creating ? <UseCaseEditor key={selected?.id ?? "new"} value={selected ?? emptyUseCase()} source={documents.find((document) => document.id === selected?.id)?.content ?? "# Use Case\n"} creating={creating} locked={locked} used={Boolean(selected && environmentUsage.includes(selected.id))} onSave={onSave} onApprove={onApprove} onDraft={onDraft} /> : <section className="rounded-md border border-dashed p-6 text-muted-foreground">Select a Use Case to inspect approval provenance and Environment usage.</section>}</div></>;
}

function UseCaseEditor({ value, source, creating, locked, used, onSave, onApprove, onDraft }: { value: UseCase; source: string; creating: boolean; locked: boolean; used: boolean; onSave(value: UseCase, markdown: string, creating: boolean): Promise<void>; onApprove(value: UseCase): Promise<void>; onDraft(value: UseCase): Promise<void> }) {
  const [draft, setDraft] = useState(value); const [markdown, setMarkdown] = useState(source); const [confirming, setConfirming] = useState(false);
  const approvalInvalidated = value.status === "approved" && useCaseApprovalHash(value) !== useCaseApprovalHash(draft);
  const setList = (key: "successGoals" | "failureGoals" | "expectedOutcomes" | "goalIds" | "adrIds" | "constraintIds", text: string) => setDraft({ ...draft, [key]: text.split(",").map((item) => item.trim()).filter(Boolean) });
  const setExample = (index: number, next: UseCaseExample) => setDraft({ ...draft, examples: draft.examples.map((example, current) => current === index ? next : example) });
  return <form className="space-y-4 rounded-md border bg-card p-4" onSubmit={(event) => { event.preventDefault(); void onSave(draft, markdown, creating); }}><div className="flex flex-wrap items-start justify-between gap-2"><div><h2 className="font-semibold">{creating ? "New draft" : draft.name}</h2><code className="text-xs text-tertiary">{draft.id || "ID required"}</code></div><OperationalStatus label={approvalInvalidated ? "Approval will be invalidated" : draft.status} tone={approvalInvalidated ? "danger" : draft.status === "approved" ? "healthy" : "attention"} /></div>
    {approvalInvalidated ? <p role="alert" className="rounded-sm border border-tertiary/50 bg-tertiary/10 p-2 text-sm">Saving semantic edits returns this Use Case to draft. Save never approves.</p> : null}
    <div className="grid gap-3 sm:grid-cols-2"><div><Label htmlFor="uc-id">Exact ID</Label><Input id="uc-id" disabled={!creating} value={draft.id} onChange={(event) => setDraft({ ...draft, id: event.target.value })} /></div><div><Label htmlFor="uc-name">Name</Label><Input id="uc-name" value={draft.name} onChange={(event) => setDraft({ ...draft, name: event.target.value })} /></div></div>
    <fieldset className="space-y-3"><legend className="font-semibold">Given–When–Then examples</legend>{draft.examples.map((example, index) => <div key={index} className="grid gap-2 rounded-sm border p-2 sm:grid-cols-3">{(["given", "when", "then"] as const).map((part) => <div key={part}><Label htmlFor={`example-${index}-${part}`}>{part}</Label><Input id={`example-${index}-${part}`} value={example[part]} onChange={(event) => setExample(index, { ...example, [part]: event.target.value })} /></div>)}<div className="flex gap-2 sm:col-span-3"><Button type="button" size="sm" variant="outline" onClick={() => setDraft({ ...draft, examples: [...draft.examples.slice(0, index), { given: "", when: "", then: "" }, ...draft.examples.slice(index)] })}>Add before</Button><Button type="button" size="sm" variant="outline" disabled={draft.examples.length === 1} onClick={() => setDraft({ ...draft, examples: draft.examples.filter((_, current) => current !== index) })}>Remove</Button></div></div>)}</fieldset>
    {(["successGoals", "failureGoals", "expectedOutcomes", "goalIds", "adrIds", "constraintIds"] as const).map((key) => <div key={key}><Label htmlFor={`uc-${key}`}>{key} · comma separated exact values</Label><Input id={`uc-${key}`} value={draft[key].join(", ")} onChange={(event) => setList(key, event.target.value)} /></div>)}
    <div><Label htmlFor="uc-markdown">Markdown source</Label><textarea id="uc-markdown" className="min-h-32 w-full rounded-sm border bg-background p-3 font-mono text-sm" value={markdown} onChange={(event) => setMarkdown(event.target.value)} /></div>
    <div className="text-xs text-muted-foreground">Environment usage: {used ? "Referenced" : "Not referenced"}. Approval hash: <code className="break-all">{useCaseApprovalHash(draft)}</code>{value.approval ? <> · approved {value.approval.approvedAt} by {value.approval.approvedBy}, revision {value.approval.revision}</> : null}</div>
    <div className="flex flex-wrap gap-2"><Button type="submit" disabled={locked || !draft.id || !draft.name}>Save draft content</Button>{!creating && value.status === "draft" ? <Button type="button" disabled={locked} onClick={() => setConfirming(true)}>Approve…</Button> : null}{value.status === "approved" ? <Button type="button" variant="outline" disabled={locked} onClick={() => void onDraft(value)}>Return to draft</Button> : null}</div>
    <Dialog open={confirming} onOpenChange={setConfirming}><DialogContent><DialogHeader><DialogTitle>Approve {draft.id}?</DialogTitle><DialogDescription>This human operation approves content version 1 with hash <code className="break-all">{useCaseApprovalHash(draft)}</code>. Saving alone never approves.</DialogDescription></DialogHeader><DialogFooter><Button variant="outline" onClick={() => setConfirming(false)}>Cancel</Button><Button onClick={() => { setConfirming(false); void onApprove(draft); }}>Approve exact content</Button></DialogFooter></DialogContent></Dialog>
  </form>;
}
