export const runtimeSchemaSupportTables = `
  CREATE TABLE execution_tasks (
    task_id TEXT PRIMARY KEY,
    provider TEXT NOT NULL CHECK(provider IN ('codex','copilot')),
    kind TEXT NOT NULL CHECK(kind = 'node_execution'),
    root_run_id TEXT NOT NULL REFERENCES root_runs(root_run_id) ON DELETE CASCADE,
    node_run_id TEXT NOT NULL REFERENCES node_runs(node_run_id),
    status TEXT NOT NULL CHECK(status IN ('queued','running','succeeded','failed','cancelled')),
    spec_json TEXT NOT NULL CHECK(json_valid(spec_json)),
    spec_hash TEXT NOT NULL CHECK(length(spec_hash) = 64),
    started_at TEXT,
    completed_at TEXT,
    cancel_requested_at TEXT,
    error_code TEXT,
    error_message TEXT,
    outcome_json TEXT CHECK(outcome_json IS NULL OR json_valid(outcome_json)),
    retained_content_bytes INTEGER NOT NULL DEFAULT 0 CHECK(retained_content_bytes >= 0),
    events_truncated INTEGER NOT NULL DEFAULT 0 CHECK(events_truncated IN (0,1)),
    last_sequence INTEGER NOT NULL DEFAULT -1,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  );
  CREATE TABLE execution_events (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    task_id TEXT NOT NULL REFERENCES execution_tasks(task_id) ON DELETE CASCADE,
    sequence INTEGER NOT NULL,
    source TEXT NOT NULL,
    kind TEXT NOT NULL,
    level TEXT NOT NULL,
    phase TEXT NOT NULL,
    item_id TEXT,
    message TEXT NOT NULL,
    data_json TEXT CHECK(data_json IS NULL OR json_valid(data_json)),
    content_bytes INTEGER NOT NULL CHECK(content_bytes >= 0),
    terminal INTEGER NOT NULL DEFAULT 0 CHECK(terminal IN (0,1)),
    created_at TEXT NOT NULL,
    UNIQUE(task_id, sequence)
  );
  CREATE TABLE repair_requests (
    repair_request_id TEXT PRIMARY KEY,
    root_run_id TEXT NOT NULL REFERENCES root_runs(root_run_id) ON DELETE CASCADE,
    requester_loop_run_id TEXT NOT NULL REFERENCES loop_invocations(loop_run_id),
    requester_job_run_id TEXT NOT NULL REFERENCES job_runs(job_run_id),
    requester_validation_node_run_id TEXT NOT NULL REFERENCES node_runs(node_run_id),
    attempt INTEGER NOT NULL CHECK(attempt > 0),
    validation_summary TEXT NOT NULL CHECK(length(trim(validation_summary)) > 0),
    requested_capability TEXT,
    requested_outcome_json TEXT CHECK(requested_outcome_json IS NULL OR json_valid(requested_outcome_json)),
    reason TEXT NOT NULL CHECK(length(trim(reason)) > 0),
    evidence_json TEXT CHECK(evidence_json IS NULL OR json_valid(evidence_json)),
    state_revision_at_request INTEGER NOT NULL CHECK(state_revision_at_request >= 0),
    orchestrator_node_run_id TEXT UNIQUE REFERENCES node_runs(node_run_id) DEFERRABLE INITIALLY DEFERRED,
    routed_loop_edge_id TEXT,
    routed_target_loop_id TEXT,
    status TEXT NOT NULL CHECK(status IN ('pending','routed','repaired','failed','cancelled')),
    return_loop_id TEXT NOT NULL,
    return_job_node_id TEXT NOT NULL,
    return_validation_node_definition_id TEXT NOT NULL,
    nesting_depth INTEGER NOT NULL CHECK(nesting_depth >= 0),
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    completed_at TEXT,
    FOREIGN KEY(root_run_id, state_revision_at_request) REFERENCES state_revisions(root_run_id, revision),
    CHECK((requested_capability IS NULL) <> (requested_outcome_json IS NULL)),
    CHECK((routed_loop_edge_id IS NULL) = (routed_target_loop_id IS NULL)),
    CHECK((status IN ('repaired','failed','cancelled')) = (completed_at IS NOT NULL))
  );
  CREATE TABLE orchestration_requests (
    orchestration_request_id TEXT PRIMARY KEY,
    root_run_id TEXT NOT NULL REFERENCES root_runs(root_run_id) ON DELETE CASCADE,
    kind TEXT NOT NULL CHECK(kind = 'repair'),
    source_loop_run_id TEXT NOT NULL REFERENCES loop_invocations(loop_run_id),
    source_loop_id TEXT NOT NULL,
    source_node_run_id TEXT NOT NULL REFERENCES node_runs(node_run_id),
    state_revision_at_request INTEGER NOT NULL CHECK(state_revision_at_request >= 0),
    completion_summary TEXT NOT NULL CHECK(length(trim(completion_summary)) > 0),
    completion_evidence_json TEXT NOT NULL CHECK(json_valid(completion_evidence_json)),
    requested_capability TEXT,
    expected_outcome_json TEXT CHECK(expected_outcome_json IS NULL OR json_valid(expected_outcome_json)),
    repair_request_id TEXT UNIQUE REFERENCES repair_requests(repair_request_id),
    orchestrator_node_run_id TEXT UNIQUE REFERENCES node_runs(node_run_id) DEFERRABLE INITIALLY DEFERRED,
    routed_loop_edge_id TEXT,
    routed_target_loop_id TEXT,
    target_loop_run_id TEXT UNIQUE REFERENCES loop_invocations(loop_run_id) DEFERRABLE INITIALLY DEFERRED,
    status TEXT NOT NULL CHECK(status IN ('pending','waiting_for_input','routed','dispatched','failed','cancelled')),
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    completed_at TEXT,
    FOREIGN KEY(root_run_id, state_revision_at_request) REFERENCES state_revisions(root_run_id, revision),
    UNIQUE(kind, source_node_run_id),
    CHECK((kind = 'repair') = (repair_request_id IS NOT NULL)),
    CHECK((routed_loop_edge_id IS NULL) = (routed_target_loop_id IS NULL)),
    CHECK((status IN ('routed','dispatched')) = (routed_loop_edge_id IS NOT NULL)),
    CHECK((status = 'dispatched') = (target_loop_run_id IS NOT NULL)),
    CHECK((status IN ('dispatched','failed','cancelled')) = (completed_at IS NOT NULL))
  );
  CREATE TABLE orchestration_frames (
    frame_id TEXT PRIMARY KEY,
    root_run_id TEXT NOT NULL REFERENCES root_runs(root_run_id) ON DELETE CASCADE,
    repair_request_id TEXT NOT NULL UNIQUE REFERENCES repair_requests(repair_request_id),
    route_id TEXT NOT NULL UNIQUE REFERENCES orchestrator_routes(route_id) DEFERRABLE INITIALLY DEFERRED,
    caller_loop_run_id TEXT NOT NULL REFERENCES loop_invocations(loop_run_id),
    callee_loop_run_id TEXT NOT NULL REFERENCES loop_invocations(loop_run_id),
    parent_frame_id TEXT REFERENCES orchestration_frames(frame_id),
    return_loop_id TEXT NOT NULL,
    return_job_node_id TEXT NOT NULL,
    return_validation_node_definition_id TEXT NOT NULL,
    state_revision_at_call INTEGER NOT NULL CHECK(state_revision_at_call >= 0),
    nesting_depth INTEGER NOT NULL CHECK(nesting_depth >= 0),
    status TEXT NOT NULL CHECK(status IN ('open','returned','failed','cancelled')),
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    completed_at TEXT,
    FOREIGN KEY(root_run_id, state_revision_at_call) REFERENCES state_revisions(root_run_id, revision),
    CHECK((status IN ('returned','failed','cancelled')) = (completed_at IS NOT NULL))
  );
  CREATE TABLE orchestrator_routes (
    route_id TEXT PRIMARY KEY,
    root_run_id TEXT NOT NULL REFERENCES root_runs(root_run_id) ON DELETE CASCADE,
    orchestration_request_id TEXT NOT NULL UNIQUE REFERENCES orchestration_requests(orchestration_request_id),
    kind TEXT NOT NULL CHECK(kind = 'repair'),
    orchestrator_node_run_id TEXT NOT NULL REFERENCES node_runs(node_run_id),
    loop_edge_id TEXT NOT NULL,
    source_loop_id TEXT NOT NULL,
    target_loop_id TEXT NOT NULL,
    route_evidence_json TEXT CHECK(route_evidence_json IS NULL OR json_valid(route_evidence_json)),
    created_at TEXT NOT NULL
  );
  CREATE TABLE repair_results (
    repair_result_id TEXT PRIMARY KEY,
    root_run_id TEXT NOT NULL REFERENCES root_runs(root_run_id) ON DELETE CASCADE,
    repair_request_id TEXT NOT NULL UNIQUE REFERENCES repair_requests(repair_request_id),
    orchestration_frame_id TEXT NOT NULL UNIQUE REFERENCES orchestration_frames(frame_id),
    target_loop_run_id TEXT NOT NULL UNIQUE REFERENCES loop_invocations(loop_run_id),
    target_loop_id TEXT NOT NULL,
    status TEXT NOT NULL CHECK(status IN ('repaired','blocked','failed','cancelled')),
    state_revision INTEGER NOT NULL CHECK(state_revision >= 0),
    outcome_json TEXT CHECK(outcome_json IS NULL OR json_valid(outcome_json)),
    summary TEXT NOT NULL CHECK(length(trim(summary)) > 0),
    created_at TEXT NOT NULL,
    FOREIGN KEY(root_run_id, state_revision) REFERENCES state_revisions(root_run_id, revision)
  );
  CREATE TABLE control_flow_events (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    root_run_id TEXT NOT NULL REFERENCES root_runs(root_run_id) ON DELETE CASCADE,
    sequence INTEGER NOT NULL CHECK(sequence BETWEEN 1 AND 2048),
    kind TEXT NOT NULL CHECK(kind IN (
      'job_completed','job_needs_input','job_terminal','validation_pass','validation_fail_retry',
      'validation_fail_escalated','validation_terminal','repair_call','repair_return','repair_terminal',
      'graph_transition','orchestrator_terminal','root_cancelled','root_terminal','execution_interrupted'
    )),
    state_revision INTEGER NOT NULL CHECK(state_revision >= 0),
    source_loop_run_id TEXT REFERENCES loop_invocations(loop_run_id),
    source_job_run_id TEXT REFERENCES job_runs(job_run_id),
    source_node_run_id TEXT REFERENCES node_runs(node_run_id),
    target_loop_run_id TEXT REFERENCES loop_invocations(loop_run_id),
    target_job_run_id TEXT REFERENCES job_runs(job_run_id),
    orchestration_request_id TEXT REFERENCES orchestration_requests(orchestration_request_id),
    repair_request_id TEXT REFERENCES repair_requests(repair_request_id),
    orchestration_frame_id TEXT REFERENCES orchestration_frames(frame_id),
    created_at TEXT NOT NULL,
    FOREIGN KEY(root_run_id, state_revision) REFERENCES state_revisions(root_run_id, revision),
    UNIQUE(root_run_id, sequence)
  );
  CREATE TABLE loop_schedule_state (
    loop_id TEXT NOT NULL,
    job_node_id TEXT NOT NULL,
    definition_hash TEXT NOT NULL,
    next_run_at TEXT,
    last_scheduled_at TEXT,
    last_status TEXT CHECK(last_status IN ('started','skipped','missed')),
    last_loop_run_id TEXT REFERENCES loop_invocations(loop_run_id) ON DELETE SET NULL,
    last_error TEXT,
    updated_at TEXT NOT NULL,
    PRIMARY KEY(loop_id, job_node_id)
  );
  CREATE TABLE graph_run_states (
    root_run_id TEXT PRIMARY KEY REFERENCES root_runs(root_run_id) ON DELETE CASCADE,
    graph_id TEXT NOT NULL,
    start_loop_id TEXT NOT NULL,
    current_loop_id TEXT,
    current_loop_run_id TEXT REFERENCES loop_invocations(loop_run_id) DEFERRABLE INITIALLY DEFERRED,
    last_transition_id TEXT,
    last_source_loop_id TEXT,
    last_decision TEXT CHECK(last_decision IN ('PASS','FAIL')),
    last_outcome TEXT,
    last_target_loop_id TEXT,
    terminal_result TEXT CHECK(terminal_result = 'DONE'),
    root_external_ref TEXT NOT NULL UNIQUE,
    root_ticket_id TEXT,
    active_loop_external_ref TEXT,
    active_loop_ticket_id TEXT,
    updated_at TEXT NOT NULL,
    CHECK((last_transition_id IS NULL) = (last_source_loop_id IS NULL)),
    CHECK((last_transition_id IS NULL) = (last_decision IS NULL)),
    CHECK((last_transition_id IS NULL) = (last_outcome IS NULL)),
    CHECK((terminal_result IS NULL) OR (current_loop_id IS NULL AND current_loop_run_id IS NULL))
  );
  CREATE TABLE tracker_links (
    link_id TEXT PRIMARY KEY,
    root_run_id TEXT NOT NULL REFERENCES root_runs(root_run_id) ON DELETE CASCADE,
    loop_run_id TEXT REFERENCES loop_invocations(loop_run_id) ON DELETE CASCADE,
    store_kind TEXT NOT NULL CHECK(store_kind IN ('orchestration','work')),
    external_ref TEXT NOT NULL,
    ticket_id TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    UNIQUE(root_run_id, store_kind, external_ref),
    UNIQUE(root_run_id, store_kind, ticket_id)
  );
  CREATE TABLE tracker_outbox (
    operation_id TEXT PRIMARY KEY,
    root_run_id TEXT NOT NULL REFERENCES root_runs(root_run_id) ON DELETE CASCADE,
    loop_run_id TEXT REFERENCES loop_invocations(loop_run_id) ON DELETE CASCADE,
    store_kind TEXT NOT NULL CHECK(store_kind IN ('orchestration','work')),
    action TEXT NOT NULL CHECK(action IN ('upsert','start','note','close','reopen')),
    external_ref TEXT NOT NULL,
    payload_json TEXT NOT NULL CHECK(json_valid(payload_json)),
    status TEXT NOT NULL CHECK(status IN ('pending','applied')),
    ticket_id TEXT,
    error_message TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    applied_at TEXT,
    UNIQUE(root_run_id, action, external_ref, payload_json),
    CHECK((status = 'applied') = (applied_at IS NOT NULL))
  );
`;
