import { ArrowLeft } from "lucide-react";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import type { ActionDefinition, ExecutionProfile } from "@shared/vnext/environment";
import type { ResourceDocument } from "../types";
import { validateActionInstruction, REQUIRED_ACTION_INSTRUCTION_SECTIONS } from "@shared/vnext/instructionContract";
import { ConfigureHeader, IssueList } from "./ConfigureHeader";
import { ActionFlow } from "./ActionFlow";

export function ActionWorkspace({ stateId, action, profiles, instructions, skills, locked, navigate, onSave }: { stateId?: string; action?: ActionDefinition; profiles: ExecutionProfile[]; instructions: ResourceDocument[]; skills: ResourceDocument[]; locked: boolean; navigate(path: string): void; onSave(action: ActionDefinition): Promise<void> }) {
  const [draft, setDraft] = useState(action);
  if (!stateId || !action || !draft) return <><ConfigureHeader title="Action not found" description="The State or Action ID in this deep link is invalid." status="Invalid ID" /><div className="p-6"><Button onClick={() => navigate("/vnext/configure/environment")}>Return to Environment</Button></div></>;
  const instructionIssues = [draft.validation, draft.work].flatMap((composition) => { const document = instructions.find((item) => item.id === composition.instructionResource); return document ? validateActionInstruction(document.content) : [{ path: composition.instructionResource, message: "Instruction resource not found" }]; });
  return <><ConfigureHeader title={action.name} description="Validation is the main controller; Work is a subordinate execution role." status={locked ? "Locked by active Run" : instructionIssues.length ? "Not ready" : "Ready"} actions={<Button variant="outline" onClick={() => navigate(`/vnext/configure/environment/states/${encodeURIComponent(stateId)}`)}><ArrowLeft />State</Button>} />
    <div className="grid min-w-0 gap-4 p-4 xl:grid-cols-[minmax(0,1.2fr)_minmax(22rem,0.8fr)] md:p-6"><div className="space-y-4"><ActionFlow action={draft} /><section className="rounded-md border bg-card p-4"><h2 className="font-semibold">Run readiness</h2><p className="mb-2 text-xs text-muted-foreground">Required instruction sections: {REQUIRED_ACTION_INSTRUCTION_SECTIONS.join(" · ")}</p><IssueList issues={instructionIssues} /></section></div>
      <form className="space-y-4 rounded-md border bg-card p-4" onSubmit={(event) => { event.preventDefault(); void onSave(draft); }}><div><h2 className="font-semibold">Action metadata</h2><code className="text-xs text-tertiary">{draft.id}</code></div>{(["name", "description"] as const).map((key) => <div key={key}><Label htmlFor={`action-${key}`}>{key}</Label><Input id={`action-${key}`} value={draft[key]} onChange={(event) => setDraft({ ...draft, [key]: event.target.value })} /></div>)}<div className="grid gap-3 sm:grid-cols-2"><div><Label htmlFor="action-priority">Priority</Label><Input id="action-priority" type="number" min={0} value={draft.priority} onChange={(event) => setDraft({ ...draft, priority: Number(event.target.value) })} /></div><div><Label htmlFor="action-retries">maxRetries</Label><Input id="action-retries" type="number" min={0} value={draft.maxRetries} onChange={(event) => setDraft({ ...draft, maxRetries: Number(event.target.value) })} /><p className="text-xs text-muted-foreground">Total maximum Work attempts: {1 + draft.maxRetries} (first attempt + {draft.maxRetries} additional).</p></div></div><div><Label htmlFor="action-refs">Use Case refs</Label><Input id="action-refs" value={draft.useCaseIds.join(", ")} onChange={(event) => setDraft({ ...draft, useCaseIds: event.target.value.split(",").map((value) => value.trim()).filter(Boolean) })} /></div>
        <CompositionEditor role="Validation" composition={draft.validation} profiles={profiles} instructions={instructions} skills={skills} onChange={(validation) => setDraft({ ...draft, validation: { ...validation, toolPolicy: "read_only" } })} /><CompositionEditor role="Work" composition={draft.work} profiles={profiles} instructions={instructions} skills={skills} onChange={(work) => setDraft({ ...draft, work: { ...work, toolPolicy: "workspace_write" } })} /><Button disabled={locked}>Save Action</Button></form></div></>;
}

function CompositionEditor({ role, composition, profiles, instructions, skills, onChange }: { role: "Validation" | "Work"; composition: ActionDefinition["validation"]; profiles: ExecutionProfile[]; instructions: ResourceDocument[]; skills: ResourceDocument[]; onChange(value: ActionDefinition["validation"]): void }) {
  return <fieldset className="space-y-2 rounded-sm border p-3"><legend className="font-semibold">{role} Agent · {role === "Validation" ? "main/controller" : "subordinate"}</legend><p className="text-xs text-muted-foreground">Permission: {role === "Validation" ? "read-only" : "workspace-write"}</p><Label>Execution profile<select aria-label={`${role} execution profile`} className="mt-1 h-10 w-full rounded-sm border bg-background px-2" value={composition.executionProfileId} onChange={(event) => onChange({ ...composition, executionProfileId: event.target.value })}>{profiles.map((profile) => <option key={profile.id} value={profile.id}>{profile.name} · {profile.model}</option>)}</select></Label><Label>Instruction<select aria-label={`${role} instruction`} className="mt-1 h-10 w-full rounded-sm border bg-background px-2" value={composition.instructionResource} onChange={(event) => onChange({ ...composition, instructionResource: event.target.value })}>{instructions.map((item) => <option key={item.id} value={item.id}>{item.id}</option>)}</select></Label><Label>Skills<Input aria-label={`${role} skills`} value={composition.skillResources.join(", ")} onChange={(event) => onChange({ ...composition, skillResources: event.target.value.split(",").map((value) => value.trim()).filter((id) => skills.some((item) => item.id === id)) })} /></Label></fieldset>;
}
