import type { ActionDefinition } from "@shared/vnext/environment";
import { OperationalStatus } from "@/components/shared/workspace-ui";

export function ActionFlow({ action }: { action: ActionDefinition }) {
  return <section aria-label={`Validation-led flow for Action ${action.id}`} className="vnext-flow rounded-md border bg-card p-4"><h2 className="mb-4 font-semibold">Validation-led authoring flow</h2><div className="mx-auto flex max-w-2xl flex-col items-center gap-2 text-center"><FlowNode label="Start" detail={action.id} /><Connector label="begins with" /><FlowNode main label="Validation · main controller" detail="Precheck: done, delegate, or blocked · read-only" /><div className="grid w-full gap-2 sm:grid-cols-2"><Branch label="valid → Done" tone="done" /><Branch label="delegate dynamic prompt" tone="delegate" /></div><Connector label="only delegate enters subordinate execution" /><FlowNode label="Work · subordinate" detail="Workspace-write · completed or needs input" /><Connector label="returns evidence to controller" /><FlowNode main label="Validation · main controller" detail="Postwork: done, retry, or blocked · read-only" /><div className="grid w-full gap-2 sm:grid-cols-3"><Branch label="valid → Done" tone="done" /><Branch label="retry → Work" tone="retry" /><Branch label="blocked → Feedback Box" tone="blocked" /></div></div><p className="mt-4 text-xs text-muted-foreground">This is an authoring projection, not runtime control. Current attempts appear only in Run.</p></section>;
}

function FlowNode({ label, detail, main = false }: { label: string; detail: string; main?: boolean }) { return <div className={`w-full rounded-md border p-3 ${main ? "border-secondary/70 bg-secondary/10" : "bg-background"}`}><strong>{label}</strong><div className="font-mono text-xs text-muted-foreground">{detail}</div>{main ? <OperationalStatus compact label="Controller role" tone="healthy" /> : null}</div>; }
function Connector({ label }: { label: string }) { return <div aria-label={label} className="flex flex-col items-center font-mono text-[0.68rem] text-muted-foreground"><span aria-hidden="true" className="h-5 border-l-2 border-canvas-flow" />{label}</div>; }
function Branch({ label, tone }: { label: string; tone: "done" | "delegate" | "retry" | "blocked" }) { return <div className={`rounded-sm border p-2 text-sm ${tone === "blocked" ? "border-destructive/60" : tone === "retry" ? "border-tertiary/60" : "border-secondary/50"}`}>{label}</div>; }
