import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Switch } from "@/components/ui/switch";
import type { CriticConfiguration, CriticScheduleDefinition } from "@shared/vnext/environment";
import { normalizeSchedule } from "../authoringModels";
import { ConfigureHeader } from "./ConfigureHeader";

export function CriticWorkspace({ critic, statuses, locked, onSave, onManual }: { critic: CriticConfiguration; statuses: Array<Record<string, unknown>>; locked: boolean; onSave(critic: CriticConfiguration): Promise<void>; onManual(): Promise<void> }) {
  const [draft, setDraft] = useState(critic); const [acknowledged, setAcknowledged] = useState(false);
  const updateSchedule = (index: number, next: CriticScheduleDefinition) => setDraft({ ...draft, schedules: draft.schedules.map((item, current) => current === index ? normalizeSchedule(next) : item) });
  return <><ConfigureHeader title="Critic configuration" description="Disabled by default. Due schedules and manual proposals run read-only; Save never runs or approves a proposal." status={draft.enabled ? "Automatic schedules enabled" : "Disabled (default)"} />
    <form className="space-y-4 p-4 md:p-6" onSubmit={(event) => { event.preventDefault(); void onSave(draft); }}><section className="rounded-md border bg-card p-4"><div className="flex items-center justify-between gap-4"><div><Label htmlFor="critic-enabled">Enable automatic Critic schedules</Label><p className="text-sm text-muted-foreground">May incur provider cost and executes automatically when locally due.</p></div><Switch id="critic-enabled" checked={draft.enabled} onCheckedChange={(checked) => setDraft({ ...draft, enabled: checked })} /></div>{draft.enabled ? <label className="mt-3 flex min-h-10 items-center gap-2 text-sm"><input type="checkbox" checked={acknowledged} onChange={(event) => setAcknowledged(event.target.checked)} />I acknowledge automatic local execution and provider cost.</label> : null}</section>
      <section className="space-y-3"><h2 className="font-semibold">Daily and weekly schedules</h2>{draft.schedules.map((schedule, index) => <fieldset key={schedule.id} className="grid gap-3 rounded-md border bg-card p-4 sm:grid-cols-2"><legend className="px-1 font-mono text-xs text-tertiary">{schedule.id}</legend><div><Label>Cadence<select aria-label={`${schedule.id} cadence`} className="mt-1 h-10 w-full rounded-sm border bg-background px-2" value={schedule.kind} onChange={(event) => updateSchedule(index, event.target.value === "daily" ? { id: schedule.id, kind: "daily", timeZone: schedule.timeZone, localTimes: schedule.localTimes } : { id: schedule.id, kind: "weekly", timeZone: schedule.timeZone, localTimes: schedule.localTimes, weekdays: [1] })}><option value="daily">Daily</option><option value="weekly">Weekly</option></select></Label></div><div><Label>IANA timezone<Input value={schedule.timeZone} onChange={(event) => updateSchedule(index, { ...schedule, timeZone: event.target.value })} /></Label></div><div><Label>Local times<Input value={schedule.localTimes.join(", ")} onChange={(event) => updateSchedule(index, { ...schedule, localTimes: event.target.value.split(",") })} /></Label></div>{schedule.kind === "weekly" ? <div><Label>ISO weekdays<Input value={schedule.weekdays.join(", ")} onChange={(event) => updateSchedule(index, { ...schedule, weekdays: event.target.value.split(",").map(Number) })} /></Label></div> : null}<p className="text-xs text-muted-foreground sm:col-span-2">Next due / last run: {JSON.stringify(statuses.find((status) => status.critic_schedule_id === schedule.id) ?? "not scheduled")}</p></fieldset>)}</section>
      <section className="rounded-md border bg-card p-4"><h2 className="font-semibold">Agent composition</h2><p className="text-sm text-muted-foreground">Profile <code>{draft.agent.executionProfileId}</code> · instruction <code>{draft.agent.instructionResource}</code> · read-only · {draft.agent.skillResources.length} Skills.</p></section>
      <div className="flex flex-wrap gap-2"><Button type="submit" disabled={locked || (draft.enabled && !acknowledged)}>Save configuration</Button><Button type="button" variant="outline" onClick={() => void onManual()}>Create critic proposal now</Button></div><p className="text-xs text-muted-foreground">Manual creation is separate from approval. It requires an existing Product Snapshot and does not create Feedback.</p></form></>;
}
