import { useEffect, useState } from "react";
import { Plus, Trash2 } from "lucide-react";
import type { DecisionOptionModelRowV2, ProjectSspDecisionStrategyV2 } from "@shared/api/workspace-contracts";
import { Alert, AlertDescription } from "@/components/ui/alert";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";

export function DecisionTransitionEditor({ strategy, actionOutcomes, locked, onChange }: {
  strategy: ProjectSspDecisionStrategyV2; actionOutcomes: Record<string, string[]>; locked: boolean;
  onChange: (strategy: ProjectSspDecisionStrategyV2) => void;
}) {
  const [addOpen, setAddOpen] = useState(false);
  const updateRows = (stateActions: DecisionOptionModelRowV2[]) => onChange({ ...strategy, model: { ...strategy.model, stateActions } });
  return <section className="grid gap-3 rounded-lg border border-divider-strong bg-card p-4">
    <div><h2 className="text-sm font-medium">Outcome-aware transitions and scalar costs</h2><p className="text-xs text-muted-foreground">Each row is P(outcome, expected next state | state, action). Priors must total exactly 1,000,000 ppm; actual state is always projected separately.</p></div>
    <div className="grid gap-2">{strategy.model.stateActions.map((row, index) => <TransitionRow key={`${row.stateId}:${row.actionId}:${index}`} row={row} strategy={strategy} actionOutcomes={actionOutcomes} locked={locked} onChange={(next) => updateRows(strategy.model.stateActions.map((candidate, candidateIndex) => candidateIndex === index ? next : candidate))} onRemove={() => updateRows(strategy.model.stateActions.filter((_, candidate) => candidate !== index))} />)}</div>
    <Button size="sm" variant="outline" disabled={locked} onClick={() => setAddOpen(true)}><Plus /> State/action row</Button>
    <TransitionRowDialog open={addOpen} onOpenChange={setAddOpen} strategy={strategy} actionOutcomes={actionOutcomes} onAdd={(row) => updateRows([...strategy.model.stateActions, row])} />
  </section>;
}

function TransitionRow({ row, strategy, actionOutcomes, locked, onChange, onRemove }: { row: DecisionOptionModelRowV2; strategy: ProjectSspDecisionStrategyV2; actionOutcomes: Record<string, string[]>; locked: boolean; onChange: (row: DecisionOptionModelRowV2) => void; onRemove: () => void }) {
  const sum = row.successors.reduce((total, branch) => total + branch.probabilityPpm, 0);
  return <div className="grid gap-2 rounded border border-divider-strong bg-background/40 p-3">
    <div className="grid gap-2 sm:grid-cols-[1fr_1fr_1fr_auto]"><NativeSelect label="State" value={row.stateId} values={strategy.model.states.filter(({ terminal }) => !terminal).map(({ id }) => id)} disabled={locked} onChange={(stateId) => onChange({ ...row, stateId })} /><NativeSelect label="Action" value={row.actionId} values={strategy.capabilityModel.actions.map(({ actionId }) => actionId)} disabled={locked} onChange={(actionId) => onChange({ ...row, actionId })} /><label className="grid gap-1 font-mono text-[0.625rem] uppercase text-muted-foreground">Cost, micro-units<Input type="number" min={1} disabled={locked} value={row.expectedCostMicros} onChange={(event) => onChange({ ...row, expectedCostMicros: Number(event.target.value) })} /></label><Button className="self-end" size="icon-sm" variant="ghost" disabled={locked} aria-label={`Remove ${row.stateId}/${row.actionId}`} onClick={onRemove}><Trash2 /></Button></div>
    {row.successors.map((branch, branchIndex) => <div key={branchIndex} className="grid gap-2 sm:grid-cols-[1fr_1fr_1fr_auto]"><NativeSelect label="Outcome" value={branch.outcomeId} values={actionOutcomes[row.actionId] ?? []} disabled={locked} onChange={(outcomeId) => onChange({ ...row, successors: replace(row.successors, branchIndex, { ...branch, outcomeId }) })} /><NativeSelect label="Expected next state" value={branch.expectedNextStateId} values={strategy.model.states.map(({ id }) => id)} disabled={locked} onChange={(expectedNextStateId) => onChange({ ...row, successors: replace(row.successors, branchIndex, { ...branch, expectedNextStateId }) })} /><label className="grid gap-1 font-mono text-[0.625rem] uppercase text-muted-foreground">Probability ppm<Input type="number" min={1} max={1_000_000} disabled={locked} value={branch.probabilityPpm} onChange={(event) => onChange({ ...row, successors: replace(row.successors, branchIndex, { ...branch, probabilityPpm: Number(event.target.value) }) })} /></label><Button className="self-end" size="icon-sm" variant="ghost" disabled={locked || row.successors.length === 1} aria-label="Remove outcome branch" onClick={() => onChange({ ...row, successors: row.successors.filter((_, candidate) => candidate !== branchIndex) })}><Trash2 /></Button></div>)}
    <div className={`font-mono text-[0.65rem] ${sum === 1_000_000 ? "text-secondary" : "text-destructive"}`}>Prior sum {sum.toLocaleString()} ppm {sum === 1_000_000 ? "✓" : "— must equal 1,000,000"}</div>
    <Button size="xs" variant="outline" disabled={locked || !actionOutcomes[row.actionId]?.[0] || !strategy.model.states[0]} onClick={() => onChange({ ...row, successors: [...row.successors, { outcomeId: actionOutcomes[row.actionId]![0]!, expectedNextStateId: strategy.model.states[0]!.id, probabilityPpm: 1 }] })}><Plus /> Outcome branch</Button>
  </div>;
}

function TransitionRowDialog({ open, onOpenChange, strategy, actionOutcomes, onAdd }: { open: boolean; onOpenChange: (open: boolean) => void; strategy: ProjectSspDecisionStrategyV2; actionOutcomes: Record<string, string[]>; onAdd: (row: DecisionOptionModelRowV2) => void }) {
  const [stateId, setStateId] = useState(""); const [actionId, setActionId] = useState(""); const [cost, setCost] = useState("");
  const [outcomeId, setOutcomeId] = useState(""); const [nextStateId, setNextStateId] = useState(""); const [probability, setProbability] = useState("");
  useEffect(() => { if (!open) { setStateId(""); setActionId(""); setCost(""); setOutcomeId(""); setNextStateId(""); setProbability(""); } }, [open]);
  const costNumber = Number(cost); const probabilityNumber = Number(probability);
  const issue = !stateId || !actionId || !outcomeId || !nextStateId ? "Choose state, action, outcome and expected next state." : !Number.isSafeInteger(costNumber) || costNumber <= 0 ? "Enter an explicit positive scalar cost." : probabilityNumber !== 1_000_000 ? "The initial branch must explicitly use 1,000,000 ppm; add branches after creating the row." : "";
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent><DialogHeader><DialogTitle>Add state/action row</DialogTitle><DialogDescription>No probabilities or costs are inferred. Enter the first explicit transition branch.</DialogDescription></DialogHeader><div className="grid gap-3 sm:grid-cols-2"><NativeSelect label="State" value={stateId} values={strategy.model.states.filter(({ terminal }) => !terminal).map(({ id }) => id)} disabled={false} onChange={setStateId} /><NativeSelect label="Action" value={actionId} values={strategy.capabilityModel.actions.map(({ actionId: id }) => id)} disabled={false} onChange={(value) => { setActionId(value); setOutcomeId(""); }} /><Field label="Cost, micro-units" value={cost} onChange={setCost} /><NativeSelect label="Outcome" value={outcomeId} values={actionOutcomes[actionId] ?? []} disabled={false} onChange={setOutcomeId} /><NativeSelect label="Expected next state" value={nextStateId} values={strategy.model.states.map(({ id }) => id)} disabled={false} onChange={setNextStateId} /><Field label="Probability ppm" value={probability} onChange={setProbability} />{issue ? <Alert variant="destructive" className="sm:col-span-2"><AlertDescription>{issue}</AlertDescription></Alert> : null}</div><DialogFooter><Button variant="outline" onClick={() => onOpenChange(false)}>Cancel</Button><Button disabled={Boolean(issue)} onClick={() => { onAdd({ stateId, actionId, expectedCostMicros: costNumber, successors: [{ outcomeId, expectedNextStateId: nextStateId, probabilityPpm: probabilityNumber }] }); onOpenChange(false); }}>Add row</Button></DialogFooter></DialogContent></Dialog>;
}

const replace = <T,>(values: T[], index: number, value: T) => values.map((candidate, candidateIndex) => candidateIndex === index ? value : candidate);
const NativeSelect = ({ label, value, values, disabled, onChange }: { label: string; value: string; values: string[]; disabled: boolean; onChange: (value: string) => void }) => <label className="grid gap-1 font-mono text-[0.625rem] uppercase text-muted-foreground">{label}<select value={value} disabled={disabled} className="h-8 min-w-0 rounded border border-input bg-background px-2 font-sans text-xs normal-case text-foreground" onChange={(event) => onChange(event.target.value)}><option value="">Choose…</option>{values.map((entry) => <option key={entry}>{entry}</option>)}</select></label>;
const Field = ({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) => <label className="grid gap-1 font-mono text-[0.625rem] uppercase text-muted-foreground">{label}<Input type="number" min={1} value={value} onChange={(event) => onChange(event.target.value)} /></label>;
