export const VNEXT_PROJECT_CONFIG_VERSION = 20 as const;
export const VNEXT_ROOT_SNAPSHOT_VERSION = 13 as const;
export const VNEXT_TASK_ENVELOPE_VERSION = 10 as const;
export const VNEXT_ROLE_OUTCOME_VERSION = 10 as const;
export const VNEXT_PROMPT_COMPOSITION_VERSION = 11 as const;
export const VNEXT_EXECUTION_SPEC_VERSION = 12 as const;
export const VNEXT_FEEDBACK_CONTRACT_VERSION = 1 as const;
export const VNEXT_CRITIC_CONTRACT_VERSION = 1 as const;
export const VNEXT_REFINEMENT_CONTRACT_VERSION = 1 as const;

export const VNEXT_VERSION_MATRIX = {
  projectConfig: VNEXT_PROJECT_CONFIG_VERSION,
  rootSnapshot: VNEXT_ROOT_SNAPSHOT_VERSION,
  taskEnvelope: VNEXT_TASK_ENVELOPE_VERSION,
  roleOutcome: VNEXT_ROLE_OUTCOME_VERSION,
  promptComposition: VNEXT_PROMPT_COMPOSITION_VERSION,
  executionSpec: VNEXT_EXECUTION_SPEC_VERSION,
  feedback: VNEXT_FEEDBACK_CONTRACT_VERSION,
  critic: VNEXT_CRITIC_CONTRACT_VERSION,
  refinement: VNEXT_REFINEMENT_CONTRACT_VERSION
} as const;
