import { render, screen, within } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { describe, expect, it, vi } from "vitest";
import { ActionWorkspace } from "../src/orchestration/configure/ActionWorkspace";
import { AgentDefinitionsWorkspace } from "../src/orchestration/configure/AgentDefinitionsWorkspace";
import { CriticWorkspace } from "../src/orchestration/configure/CriticWorkspace";
import { DirectionWorkspace } from "../src/orchestration/configure/DirectionWorkspace";
import { EnvironmentWorkspace } from "../src/orchestration/configure/EnvironmentWorkspace";
import { ResourceWorkspace } from "../src/orchestration/configure/ResourceWorkspace";
import { StateWorkspace } from "../src/orchestration/configure/StateWorkspace";
import { UseCasesWorkspace } from "../src/orchestration/configure/UseCasesWorkspace";
import { OrchestrationSidebar } from "../src/orchestration/OrchestrationSidebar";
import { SidebarProvider } from "../src/components/ui/sidebar";
import { orchestrationApi, orchestrationApiBase } from "../src/orchestration/orchestrationApi";
import { resources, orchestrationConfig } from "./orchestrationFixtures";

const directionProps = () => { const config = orchestrationConfig(); return { direction: config.direction, documents: { goals: [{ kind: "goal" as const, id: "goal-1", content: "# Goal", contentHash: "a".repeat(64) }], adrs: [], constraints: [] }, references: [], locked: false, onSave: vi.fn(), onDelete: vi.fn() }; };

describe("orchestration Configure UI", () => {
  it("renders Direction list/detail selection", async () => { const user = userEvent.setup(); render(<DirectionWorkspace {...directionProps()} />); await user.click(screen.getByRole("button", { name: /goal-1 Goal/ })); expect(screen.getByRole("heading", { name: "Edit goal-1" })).toBeInTheDocument(); });
  it("renders Constraint kind and status as text", async () => { const user = userEvent.setup(); render(<DirectionWorkspace {...directionProps()} />); await user.click(screen.getByRole("button", { name: /constraint-1 No skip/ })); expect(screen.getByLabelText("Constraint semantics")).toHaveValue("prohibited"); expect(screen.getAllByText("accepted").length).toBeGreaterThan(0); });
  it("disables Direction delete when references exist", async () => { const user = userEvent.setup(); const props = directionProps(); props.references = [{ kind: "goal", id: "goal-1", references: [{ ownerType: "use-case", ownerId: "UC-1", field: "goalIds" }] }]; render(<DirectionWorkspace {...props} />); await user.click(screen.getByRole("button", { name: /goal-1 Goal/ })); expect(screen.getByRole("button", { name: "Delete" })).toBeDisabled(); });
  it("renders Use Case draft editing", async () => { const user = userEvent.setup(); const config = orchestrationConfig(); const draft = { ...config.direction.useCases[0]!, status: "draft" as const, approval: undefined }; render(<UseCasesWorkspace useCases={[draft]} documents={[]} locked={false} environmentUsage={[]} onSave={vi.fn()} onApprove={vi.fn()} onDraft={vi.fn()} />); await user.click(screen.getByRole("button", { name: /UC-1/ })); expect(screen.getByLabelText("Name")).toHaveValue("Deliver outcome"); expect(screen.getByRole("button", { name: "Save draft content" })).toBeInTheDocument(); expect(screen.getByRole("button", { name: "Approve…" })).toBeInTheDocument(); });
  it("requires explicit Use Case approval confirmation with hash", async () => { const user = userEvent.setup(); const config = orchestrationConfig(); const draft = { ...config.direction.useCases[0]!, status: "draft" as const, approval: undefined }; const approve = vi.fn(); render(<UseCasesWorkspace useCases={[draft]} documents={[]} locked={false} environmentUsage={[]} onSave={vi.fn()} onApprove={approve} onDraft={vi.fn()} />); await user.click(screen.getByRole("button", { name: /UC-1/ })); await user.click(screen.getByRole("button", { name: "Approve…" })); expect(screen.getByRole("dialog")).toHaveTextContent(/[a-f0-9]{64}/); await user.click(screen.getByRole("button", { name: "Approve exact content" })); expect(approve).toHaveBeenCalledOnce(); });
  it("warns that an approved semantic edit returns to draft", async () => { const user = userEvent.setup(); const useCase = orchestrationConfig().direction.useCases[0]!; render(<UseCasesWorkspace useCases={[useCase]} documents={[]} locked={false} environmentUsage={[useCase.id]} onSave={vi.fn()} onApprove={vi.fn()} onDraft={vi.fn()} />); await user.click(screen.getByRole("button", { name: /UC-1/ })); await user.clear(screen.getByLabelText("Name")); await user.type(screen.getByLabelText("Name"), "Changed"); expect(screen.getByRole("alert")).toHaveTextContent("returns this Use Case to draft"); });
  it("renders Environment States in ascending order", () => { const config = orchestrationConfig(); render(<EnvironmentWorkspace environment={{ ...config.environment, states: [...config.environment.states].reverse() }} issues={[]} locked={false} navigate={vi.fn()} onMove={vi.fn()} />); const lanes = screen.getByRole("region", { name: "Ordered State lanes" }); const codes = within(lanes).getAllByText(/ORDER/); expect(codes[0]).toHaveTextContent("ORDER 1"); expect(codes[1]).toHaveTextContent("ORDER 2"); });
  it("owns authoring collection selection in the canonical sidebar URL", async () => { window.history.replaceState({}, "", "/agents?id=profile-1"); const user = userEvent.setup(); const navigate = vi.fn(); const config = orchestrationConfig(); const data = { project: { path: "/project", config, configHash: "a".repeat(64) }, references: { entries: [], runReferences: [], activeRunIds: [] }, instructions: resources().filter(({ kind }) => kind === "instruction"), skills: resources().filter(({ kind }) => kind === "skill"), goals: [], adrs: [], constraints: [], useCases: [], agents: [], schedules: [] }; render(<SidebarProvider><OrchestrationSidebar route={{ view: "orchestration", workspaceView: "agents", entityId: "profile-1" }} data={data} navigate={navigate} /></SidebarProvider>); const entity = screen.getByRole("button", { name: /PrimaryEnabled/ }); expect(entity).toHaveAttribute("aria-current", "page"); await user.click(entity); expect(navigate).toHaveBeenCalledWith("/agents?id=profile-1"); });
  it("supports keyboard activation for State reorder in the detail toolbar", async () => { const user = userEvent.setup(); const move = vi.fn(); const state = orchestrationConfig().environment.states[1]!; render(<StateWorkspace state={state} locked={false} canMoveEarlier navigate={vi.fn()} onSave={vi.fn()} onMove={move} onCreateAction={vi.fn()} onDelete={vi.fn()} />); const button = screen.getByRole("button", { name: "Earlier" }); button.focus(); await user.keyboard("{Enter}"); expect(move).toHaveBeenCalledWith(-1); expect(screen.getAllByRole("toolbar")).toHaveLength(1); });
  it("renders State Actions by priority", () => { const state = orchestrationConfig().environment.states[0]!; const second = { ...state.actions[0]!, id: "action-0", priority: 2 }; render(<StateWorkspace state={{ ...state, actions: [second, state.actions[0]!] }} locked={false} navigate={vi.fn()} onSave={vi.fn()} onMoveAction={vi.fn()} />); const ids = screen.getAllByText(/PRIORITY/); expect(ids[0]).toHaveTextContent("action-1"); });
  it("presents Validation as main and Work as subordinate", () => { renderAction(); expect(screen.getByText("Validation Agent · main/controller")).toBeInTheDocument(); expect(screen.getByText("Work Agent · subordinate")).toBeInTheDocument(); });
  it("uses only the workspace title for Action metadata", () => { renderAction(); expect(screen.getAllByRole("heading", { name: "Implement" })).toHaveLength(1); expect(screen.queryByText("Action metadata")).not.toBeInTheDocument(); });
  it("explains the total attempts derived from maxRetries", () => { renderAction(); expect(screen.getByText("Total maximum Work attempts: 3")).toBeInTheDocument(); });
  it("reports missing instruction sections", () => { const config = orchestrationConfig(); render(<ActionWorkspace stateId="state-1" action={config.environment.states[0]!.actions[0]} profiles={config.agents} instructions={[{ ...resources()[0]!, content: "# Missing" }, resources()[1]!]} skills={[resources()[2]!]} locked={false} navigate={vi.fn()} onCanvasModeChange={vi.fn()} onSave={vi.fn()} />); expect(screen.getByRole("alert")).toHaveTextContent("Missing Task section"); });
  it("opens and closes the Action flow with an accessible control", async () => { const user = userEvent.setup(); const changeMode = vi.fn(); const config = orchestrationConfig(); const props = { stateId: "state-1", action: config.environment.states[0]!.actions[0], profiles: config.agents, instructions: resources().filter((item) => item.kind === "instruction"), skills: resources().filter((item) => item.kind === "skill"), locked: false, navigate: vi.fn(), onCanvasModeChange: changeMode, onSave: vi.fn() }; const { rerender } = render(<ActionWorkspace {...props} />); await user.click(screen.getByRole("button", { name: "Open Action flow" })); expect(changeMode).toHaveBeenCalledWith("flow"); await user.type(screen.getByLabelText("Name"), " draft"); rerender(<ActionWorkspace {...props} canvasMode="flow" />); expect(screen.getByLabelText("Name")).toHaveValue(`${props.action.name} draft`); await user.click(screen.getByRole("button", { name: "Show space canvas" })); expect(changeMode).toHaveBeenLastCalledWith("space"); });
  it("locks authoring controls during an active Run", () => { renderAction(true); expect(screen.getByRole("button", { name: "Save Action" })).toBeDisabled(); expect(screen.getByText("Locked by active Run")).toBeInTheDocument(); });
  it("keeps a dirty resource draft when refreshed props arrive", async () => { const user = userEvent.setup(); const resource = resources()[0]!; const navigate = vi.fn(); const { rerender } = render(<ResourceWorkspace kind="instructions" resources={[resource]} references={[]} locked={false} selectedId="validation" navigate={navigate} onSave={vi.fn()} />); await user.type(screen.getByLabelText("Markdown Body"), "\nlocal draft"); rerender(<ResourceWorkspace kind="instructions" resources={[{ ...resource, content: `${resource.content}\nserver refresh` }]} references={[]} locked={false} selectedId="validation" navigate={navigate} onSave={vi.fn()} />); expect(screen.getByLabelText("Markdown Body")).toHaveValue(`${resource.content.trimEnd()}\nlocal draft`); });
  it("restores the compact Agent profile, Preview and editor composition", async () => { vi.spyOn(orchestrationApi, "runtimeDevices").mockResolvedValue([]); vi.spyOn(orchestrationApi, "agentBinding").mockResolvedValue(null); const agent = orchestrationConfig().agents[0]!; const content = `---\nid: ${agent.id}\ntitle: ${agent.name}\ndescription: ${agent.description}\nstatus: active\nenabled: true\ninstructionResource: ${agent.instructionResource}\nskillResources: [${agent.skillResources.join(", ")}]\n---\n# ${agent.name}\n${agent.description}`; render(<AgentDefinitionsWorkspace profiles={[agent]} documents={[{ kind: "agent", id: agent.id, content, contentHash: "d".repeat(64) }]} references={[]} selectedId={agent.id} locked={false} navigate={vi.fn()} onSave={vi.fn()} onDelete={vi.fn()} />); expect(screen.getByRole("complementary", { name: "Agent profile" })).toHaveTextContent(agent.id); expect(screen.getByRole("region", { name: "Agent execution settings" })).toBeInTheDocument(); expect(screen.getByText("Preview")).toBeInTheDocument(); expect(screen.getByText("Markdown Workbench")).toBeInTheDocument(); expect(screen.getAllByRole("toolbar")).toHaveLength(1); });
  it("shows shared Skill impact warning", () => { render(<ResourceWorkspace kind="skills" resources={[resources()[2]!]} references={[{ kind: "skill", id: "shared-skill", references: [{ ownerType: "action", ownerId: "action-1", field: "validation.skillResources" }] }]} locked={false} selectedId="shared-skill" navigate={vi.fn()} onSave={vi.fn()} />); expect(screen.getByRole("alert")).toHaveTextContent("impacts 1 referencing role"); });
  it("renders Critic disabled by default", () => { const config = orchestrationConfig(); render(<CriticWorkspace critic={config.critic} statuses={[]} locked={false} onSave={vi.fn()} onManual={vi.fn()} />); expect(screen.getByText("Disabled (default)")).toBeInTheDocument(); expect(screen.getByRole("switch", { name: "Enable automatic Critic schedules" })).toHaveAttribute("aria-checked", "false"); });
  it("edits a Critic IANA timezone", async () => { const user = userEvent.setup(); const config = orchestrationConfig(); render(<CriticWorkspace critic={config.critic} statuses={[]} locked={false} onSave={vi.fn()} onManual={vi.fn()} />); const zone = screen.getByLabelText("IANA timezone"); await user.clear(zone); await user.type(zone, "UTC"); expect(zone).toHaveValue("UTC"); });
  it("keeps manual Critic creation separate from approval", async () => { const user = userEvent.setup(); const manual = vi.fn(); const config = orchestrationConfig(); render(<CriticWorkspace critic={config.critic} statuses={[]} locked={false} onSave={vi.fn()} onManual={manual} />); await user.click(screen.getByRole("button", { name: "Create critic proposal now" })); expect(manual).toHaveBeenCalledOnce(); expect(screen.queryByRole("button", { name: /approve/i })).not.toBeInTheDocument(); });
  it("renders invalid State deep links with recovery", () => { render(<StateWorkspace locked={false} navigate={vi.fn()} onSave={vi.fn()} onMoveAction={vi.fn()} />); expect(screen.getByRole("heading", { name: "State not found" })).toBeInTheDocument(); expect(screen.getByRole("button", { name: "Return to Environment" })).toBeInTheDocument(); });
  it("keeps core actions in one responsive toolbar", () => { renderAction(); const save = screen.getByRole("button", { name: "Save Action" }); expect(save).toHaveAttribute("form", "action-action-1"); expect(screen.getAllByRole("toolbar")).toHaveLength(1); expect(screen.getByRole("button", { name: "Open Action flow" })).toBeInTheDocument(); });
  it("uses the canonical API prefix in orchestration data modules", () => { expect(orchestrationApiBase).toBe("/api"); });
  it("associates Action fields with labels", () => { renderAction(); expect(screen.getByLabelText("maxRetries")).toHaveAttribute("type", "number"); const validation = screen.getByRole("group", { name: "Validation Agent · main/controller" }); expect(within(validation).getByLabelText("Agent")).toHaveTextContent("Primary"); });
});

function renderAction(locked = false) { const config = orchestrationConfig(); render(<ActionWorkspace stateId="state-1" action={config.environment.states[0]!.actions[0]} profiles={config.agents} instructions={resources().filter((item) => item.kind === "instruction")} skills={resources().filter((item) => item.kind === "skill")} locked={locked} navigate={vi.fn()} onCanvasModeChange={vi.fn()} onSave={vi.fn()} />); }
