import { render, screen, within } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { describe, expect, it, vi } from "vitest";
import { CriticReviewWorkspace } from "../src/vnext/run/CriticReviewWorkspace";
import { FeedbackWorkspace } from "../src/vnext/run/FeedbackWorkspace";
import { ProductWorkspace } from "../src/vnext/run/ProductWorkspace";
import { RefinementReviewWorkspace } from "../src/vnext/run/RefinementReviewWorkspace";
import { RunDetailWorkspace } from "../src/vnext/run/RunDetailWorkspace";
import { RunListWorkspace } from "../src/vnext/run/RunListWorkspace";
import type { JsonRow, RunDetail, RunSummary } from "../src/vnext/runTypes";
import { vNextConfig } from "./vnextFixtures";

const summary = (overrides: Partial<RunSummary> = {}): RunSummary => ({ environmentRunId: "run-1", environmentDefinitionId: "environment-1", source: "manual", status: "running", revision: 2, baseCommit: "base", branch: "ballet/run-1", transitionCount: 3, transitionLimit: 100, createdAt: "2026-01-01", updatedAt: "2026-01-02", ...overrides });
const detail = (overrides: Partial<RunDetail> = {}): RunDetail => ({ ...summary(), states: [
  { stateExecutionId: "sx-2", stateDefinitionId: "state-2", order: 2, status: "pending", revision: 0, createdAt: "now", updatedAt: "now", done: false, blocked: false, actions: [{ actionExecutionId: "ax-2", actionDefinitionId: "action-2", priority: 2, status: "pending", revision: 0, workAttempt: 0, maxRetries: 1, createdAt: "now", updatedAt: "now", done: false, blocked: false }] },
  { stateExecutionId: "sx-1", stateDefinitionId: "state-1", order: 1, status: "running", revision: 1, createdAt: "now", updatedAt: "now", done: false, blocked: false, actions: [{ actionExecutionId: "ax-1", actionDefinitionId: "action-1", priority: 1, status: "retrying", revision: 2, workAttempt: 2, maxRetries: 2, createdAt: "now", updatedAt: "now", done: false, blocked: false }] }
], events: [{ actionExecutionId: "ax-1", sequence: 1, kind: "validation_precheck_delegate", createdAt: "one" }, { actionExecutionId: "ax-1", sequence: 2, kind: "work_started", createdAt: "two" }, { actionExecutionId: "ax-1", sequence: 3, kind: "validation_postwork_retry", createdAt: "three" }], ...overrides });
const feedback = (overrides: JsonRow = {}): JsonRow => ({ feedback_entry_id: "feedback-1", environment_run_id: "run-1", action_execution_id: "ax-1", source: "runtime", category: "product", target_type: "action_execution", target_id: "ax-1", title: "Blocked action", description: "Exact reason", corrective_actions_json: JSON.stringify(["Correct it"]), evidence_refs_json: JSON.stringify(["event:3"]), provenance_json: "{}", status: "open", created_at: "now", ...overrides });
const critic = (): JsonRow => ({ critic_proposal_id: "critic-1", critic_run_id: "critic-run-1", target_type: "action", target_id: "action-1", category: "code", status: "pending_human_review", content_hash: "c".repeat(64), version: 1, created_at: "now", content_json: JSON.stringify({ title: "Finding", finding: "Problem", severity: "high", confidence: 0.9, evidenceRefs: ["file:1"], recommendedCorrectiveActions: ["Change it"], rationale: "Because" }) });
const refinement = (status = "pending_human_review"): JsonRow => ({ refinement_proposal_id: "refine-1", refinement_run_id: "refine-run-1", target_action_id: "action-1", status, expected_base_commit: "base", change_list_hash: "l".repeat(64), impact_scope_json: JSON.stringify({ actionIds: ["action-1"] }), expected_behavioral_improvement: "Improve behavior", validation_plan_json: JSON.stringify(["npm test"]), risks_json: JSON.stringify(["Risk"]), rollback: "Discard branch", version: 1, created_at: "now", files: [{ operation: "update", relative_path: ".ballet/instructions/action.md", expected_preimage_hash: "old", proposed_content_hash: "new", proposed_content: "# Goal\nExact bytes" }] });

describe("vNext Run and governance UI", () => {
  it("offers only full Environment start and blocks it on readiness issues", async () => { const user = userEvent.setup(); render(<RunListWorkspace runs={[]} environment={vNextConfig().environment} issues={[{ path: "environment", code: "blocked", message: "Direction is incomplete" }]} configHash="hash" navigate={vi.fn()} onStart={vi.fn()} />); expect(screen.getByRole("button", { name: "Start Environment…" })).toBeInTheDocument(); expect(screen.queryByText(/Start State|Start Action/)).not.toBeInTheDocument(); await user.click(screen.getByRole("button", { name: "Start Environment…" })); expect(screen.getByRole("button", { name: "Start Environment" })).toBeDisabled(); expect(screen.getByRole("dialog")).toHaveTextContent("Direction is incomplete"); });
  it("renders State gate and Actions in ascending deterministic order", () => { render(<RunDetailWorkspace run={detail()} feedback={[]} navigate={vi.fn()} onCancel={vi.fn()} />); const gate = screen.getByRole("region", { name: "Ordered State gate" }); const orders = within(gate).getAllByText(/ORDER/); expect(orders[0]).toHaveTextContent("ORDER 1"); expect(orders[1]).toHaveTextContent("ORDER 2"); expect(gate).toHaveTextContent("Gated by an earlier State"); });
  it("shows Validation-led retry timeline and additional-attempt formula", () => { render(<RunDetailWorkspace run={detail()} feedback={[]} navigate={vi.fn()} onCancel={vi.fn()} />); const timeline = screen.getByRole("region", { name: "Action action-1 execution timeline" }); expect(timeline).toHaveTextContent("Validation · main"); expect(timeline).toHaveTextContent("Work · subordinate"); expect(timeline).toHaveTextContent("Work attempt 2 / 3"); expect(timeline).toHaveTextContent("Retries used 1 · remaining 1"); });
  it("renders precheck done without inventing a Work step", () => { const run = detail({ events: [{ actionExecutionId: "ax-1", sequence: 1, kind: "validation_precheck_done", createdAt: "one" }] }); render(<RunDetailWorkspace run={run} feedback={[]} navigate={vi.fn()} onCancel={vi.fn()} />); expect(screen.getByText("validation_precheck_done")).toBeInTheDocument(); expect(screen.queryByText("work_started")).not.toBeInTheDocument(); });
  it("explains a blocked Action, Feedback path, and absence of force-done", () => { const run = detail(); run.states[1]!.actions[0] = { ...run.states[1]!.actions[0]!, status: "blocked", blocked: true }; render(<RunDetailWorkspace run={{ ...run, status: "blocked" }} feedback={[feedback()]} navigate={vi.fn()} onCancel={vi.fn()} />); expect(screen.getByText(/Blocked · later States remain gated/)).toBeInTheDocument(); expect(screen.getByText(/There is no force-done command/)).toBeInTheDocument(); expect(screen.queryByRole("button", { name: /force/i })).not.toBeInTheDocument(); });
  it("creates human Feedback with fixed source semantics and selected category", async () => { const user = userEvent.setup(); const create = vi.fn(); render(<FeedbackWorkspace rows={[]} runs={[summary()]} navigate={vi.fn()} onCreate={create} onDecision={vi.fn()} onRefinement={vi.fn()} />); await user.click(screen.getByRole("button", { name: "Add human Feedback" })); expect(screen.getByText(/Source is fixed to/)).toHaveTextContent("human"); await user.selectOptions(screen.getByLabelText("Feedback category"), "architecture"); await user.type(screen.getByLabelText("Title"), "Review architecture"); await user.type(screen.getByLabelText("Description"), "Description"); await user.type(screen.getByLabelText("Corrective actions"), "Correct one"); await user.click(screen.getByRole("button", { name: "Create human Feedback" })); expect(create).toHaveBeenCalledWith(expect.objectContaining({ category: "architecture", environmentRunId: "run-1" })); expect(create.mock.calls[0]?.[0]).not.toHaveProperty("source"); });
  it("keeps pending Critic proposal separate from Feedback", () => { render(<CriticReviewWorkspace proposals={[critic()]} runs={[summary()]} navigate={vi.fn()} onDecision={vi.fn()} />); expect(screen.getByText("No Feedback exists before approval.")).toBeInTheDocument(); });
  it("confirms Critic approval against exact hash and consequence", async () => { const user = userEvent.setup(); const decide = vi.fn(); render(<CriticReviewWorkspace proposals={[critic()]} selected={critic()} runs={[summary()]} navigate={vi.fn()} onDecision={decide} />); await user.click(screen.getByRole("button", { name: "Approve…" })); expect(screen.getByRole("dialog")).toHaveTextContent("Duplicate or stale decisions are rejected"); expect(screen.getByRole("dialog")).toHaveTextContent("c".repeat(64)); await user.click(screen.getByRole("button", { name: "Confirm approved" })); expect(decide).toHaveBeenCalledWith("critic-1", expect.objectContaining({ expectedContentHash: "c".repeat(64), feedback: expect.objectContaining({ feedbackEntryId: "feedback-critic-1" }) })); });
  it("renders exact Refinement changes, hashes, impact, and text diff markers", () => { render(<RefinementReviewWorkspace proposals={[refinement()]} selected={refinement()} feedback={[feedback({ refinement_proposal_id: "refine-1" })]} navigate={vi.fn()} onDecision={vi.fn()} onApply={vi.fn()} />); expect(screen.getByText(".ballet/instructions/action.md", { exact: false })).toBeInTheDocument(); expect(screen.getByText(/Change-list hash/)).toHaveTextContent("l".repeat(64)); expect(screen.getByText(/Exact impacted Actions/)).toHaveTextContent("action-1"); expect(screen.getAllByLabelText("added line")).toHaveLength(2); });
  it("requires acknowledgment before exact Refinement approval", async () => { const user = userEvent.setup(); const decide = vi.fn(); render(<RefinementReviewWorkspace proposals={[refinement()]} selected={refinement()} feedback={[]} navigate={vi.fn()} onDecision={decide} onApply={vi.fn()} />); await user.click(screen.getByRole("button", { name: "Approve exact refinement…" })); const confirm = screen.getByRole("button", { name: "Confirm approved" }); expect(confirm).toBeDisabled(); await user.click(screen.getByRole("checkbox")); await user.click(confirm); expect(decide).toHaveBeenCalledWith("refine-1", expect.objectContaining({ expectedContentHash: "l".repeat(64), expectedChangeHashes: ["new"], expectedImpactActionIds: ["action-1"], acknowledgeLocalCommitAndContinuation: true })); });
  it.each([["applying", "Apply approved proposal"], ["apply_failed", "No partial write is asserted"]])("shows %s apply state", (status, expected) => { render(<RefinementReviewWorkspace proposals={[refinement(status)]} selected={refinement(status)} feedback={[]} applyStatus={{ status }} navigate={vi.fn()} onDecision={vi.fn()} onApply={vi.fn()} />); expect(screen.getByText(expected, { exact: false })).toBeInTheDocument(); });
  it("links an applied proposal to its immutable continuation Run", () => { const navigate = vi.fn(); render(<RefinementReviewWorkspace proposals={[refinement("applied")]} selected={refinement("applied")} feedback={[]} applyStatus={{ status: "applied" }} continuation={{ continuation_run_id: "run-2" }} navigate={navigate} onDecision={vi.fn()} onApply={vi.fn()} />); expect(screen.getByRole("button", { name: "Open continuation Run" })).toBeInTheDocument(); expect(screen.getByText(/Feedback context/).parentElement?.parentElement).toHaveTextContent("Feedback"); });
  it("states Feedback resolution waits for verified continuation evidence", () => { render(<FeedbackWorkspace rows={[feedback({ status: "in_refinement" })]} runs={[summary()]} selected={feedback({ status: "in_refinement" })} navigate={vi.fn()} onCreate={vi.fn()} onDecision={vi.fn()} onRefinement={vi.fn()} />); expect(screen.getByText(/resolved only after verified continuation evidence/)).toBeInTheDocument(); });
  it("renders Product Snapshot evidence and local-only review boundary", () => { const product = { product_snapshot_id: "product-1", environment_run_id: "run-1", base_commit: "base", result_commit: "result", branch: "ballet/run-1", worktree_path: "/tmp/worktree", changed_files_json: "[]", artifact_refs_json: "[]", resource_hashes_json: "{}", definition_hashes_json: "{}", validation_summary_json: "{}", created_at: "now" }; render(<ProductWorkspace products={[product]} selected={product} runs={[summary({ status: "completed", resultCommit: "result" })]} navigate={vi.fn()} />); expect(screen.getByRole("heading", { name: "product-1" })).toBeInTheDocument(); expect(screen.getByText(/no merge, push, release, or deploy command/)).toBeInTheDocument(); });
  it("recovers from invalid Run and Product deep links", () => { const { rerender } = render(<RunDetailWorkspace feedback={[]} navigate={vi.fn()} onCancel={vi.fn()} />); expect(screen.getByRole("heading", { name: "Run not found" })).toBeInTheDocument(); rerender(<ProductWorkspace products={[]} selectedId="missing" runs={[]} navigate={vi.fn()} />); expect(screen.getByRole("heading", { name: "Snapshot not found" })).toBeInTheDocument(); });
  it("keeps responsive core panels free of old Graph/MDP terminology", () => { const { container } = render(<RunDetailWorkspace run={detail()} feedback={[]} navigate={vi.fn()} onCancel={vi.fn()} />); expect(container.textContent).not.toMatch(/GraphNode|ActionNode|Reward-MDP|policy matrix/); const gate = screen.getByRole("region", { name: "Ordered State gate" }); expect(gate).toContainElement(within(gate).getAllByRole("list")[0]!); });
});
